<<<<<<< HEAD
version: '3.8'

services:
  myredsiapp:
    image: 677276101053.dkr.ecr.eu-north-1.amazonaws.com/myredisapp:2
    

  redis-server-stackm:
    image: redis/redis-stack:latest
    ports:  
      - 6379:6379
      - 8000:8001
    volumes: 
      - redis-data:/data/db
    
volumes:
  redis-data:
    driver: local
=======
version: '3.8'

services:
 
  redis-server-stackm:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes: 
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
>>>>>>> e3476a6ccf315f8b7a4b2102ad12dfe1acb61df1
